### ISSUE TITLE
"file is not in your workspace" in windows

### ISSUE THREAD

**Issue by handiao** [dlutwuwei/upload#4]
I have not test your project in local, is here something wrong? 
`if (!config.localPath && (workspace.rootPath == null || uri.path.indexOf(workspace.rootPath) != 0)) {
        window.showInformationMessage('file is not in your workspace');
        return null;
    }`

**Comment by dlutwuwei** [comment]
@handiao 没有配置localpath且文件路径不在workspace.rootpath里，有什么问题吗？

**Comment by dlutwuwei** [comment]
I have fixed it, thx
